### ISSUE TITLE
Make it so that if a user doesn't select a timeframe from the dropdown, it defaults to '30d'

### ISSUE THREAD

**Issue by donmox** [FHDevelopment/fhtrueiq#1]
Nathan is resaving form with 7day selection.   If this works, we will delete the data from all of patheon2, fhtrueiq, and other sites.   Delete the lists.  Retract solutions.  Redeploy and rebuild.

**Comment by njosefbeck** [comment]
This is now a required field, so the form won't save unless a user selects a timeframe from the dropdown. Fixed.
